### ISSUE TITLE
Suggestion: Mark Start Vertex

### ISSUE THREAD

**Issue by Talia-12** [Robotgiggle/hex-interpreter#1]
When rendering the pattern for an inputted pattern string, it'd be nice if the start vertex was highlighted somehow so it's easier to see.

**Comment by Robotgiggle** [comment]
The first line of a pattern has a larger triangle indicator, and it also has the triangle despite not changing colors. If you look for that, you can find the beginning of the pattern.

**Comment by Robotgiggle** [comment]
After some other comments on the discord to add the feature you suggested, I've done so. The start and end of the pattern are now marked with special dots that match the color of the connected line.
