### ISSUE TITLE
Can u add logfile?

### ISSUE THREAD

**Issue by MaxLevs** [Robotgiggle/hex-interpreter#2]
Programm starts and exits immediately. I have no idea why

**Comment by Robotgiggle** [comment]
Double-clicking on the `hex_draw.py` file, which causes a popup that immediately exits, is not how you run the tool. Python scripts are run using the `python` terminal command. Open your command line, navigate to the folder containing the script, and then run `python hex_draw.py`.

(I should probably add this to the readme)

**Comment by MaxLevs** [comment]
Yeah. This is literally how I run python scripts.

```
> .\hex_draw.py
```

**Comment by MaxLevs** [comment]
Ok. This is my mistake. But yeah "Usage" section can come in handy in times like this. Or `-h` arg.
